//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock.Models.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRM
    {
        public int ID { get; set; }
        public string FIRM_NAME { get; set; }
        public string ADRESS { get; set; }
        public Nullable<bool> IS_DELETED { get; set; }
    }
}
