//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock.Models.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARKURS
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> DolarPrice { get; set; }
        public Nullable<decimal> EuroPrice { get; set; }
        public Nullable<decimal> PoundPrice { get; set; }
        public Nullable<decimal> TurkishLiraPrice { get; set; }
        public Nullable<decimal> RublePrice { get; set; }
    }
}
