//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock.Models.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARKURS_USERS
    {
        public int ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string USER_SURNAME { get; set; }
        public Nullable<int> PARKUR_ID { get; set; }
        public Nullable<int> KUR_ID { get; set; }
        public string KUR_CODE { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    }
}
