//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock.Models.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string BarcodeNumber { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Date { get; set; }
        public Nullable<int> ScannedBy { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string Description { get; set; }
    }
}
