//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock.Models.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string USER_CODE { get; set; }
        public Nullable<int> IS_SUPER_USER { get; set; }
        public Nullable<bool> IS_DELETED { get; set; }
        public string PASSWORD { get; set; }
    }
}
